"""Factory builders and helpers for E2E scenario construction."""

from typing import Any, Callable, Optional

from mas.domain.plan import Plan, Step
from mas.domain.task import Task
from mas.runtime.executor import StepResult


class TaskBuilder:
    """Fluent builder for creating realistic Task objects."""

    def __init__(self) -> None:
        self._id = "task-default"
        self._description = "Test task"
        self._goal = "Complete the task"
        self._context: dict[str, Any] = {}
        self._metadata: dict[str, Any] = {}

    def with_id(self, task_id: str) -> "TaskBuilder":
        """Set task ID."""
        self._id = task_id
        return self

    def with_description(self, description: str) -> "TaskBuilder":
        """Set task description."""
        self._description = description
        return self

    def with_goal(self, goal: str) -> "TaskBuilder":
        """Set task goal."""
        self._goal = goal
        return self

    def with_context(self, context: dict[str, Any]) -> "TaskBuilder":
        """Set task context."""
        self._context = context
        return self

    def with_metadata(self, metadata: dict[str, Any]) -> "TaskBuilder":
        """Set task metadata."""
        self._metadata = metadata
        return self

    def build(self) -> Task:
        """Build the Task object."""
        task = Task(
            id=self._id,
            description=self._description,
            goal=self._goal,
        )
        task.context = self._context
        task.metadata = self._metadata
        return task


class StepBuilder:
    """Fluent builder for creating Step objects."""

    def __init__(self, step_id: str) -> None:
        self._id = step_id
        self._action = "default_action"
        self._inputs: dict[str, Any] = {}
        self._depends_on: list[str] = []
        self._metadata: dict[str, Any] = {"cost": 1.0}
        self._max_retries = 0

    def with_action(self, action: str) -> "StepBuilder":
        """Set step action."""
        self._action = action
        return self

    def with_cost(self, cost: float) -> "StepBuilder":
        """Set step cost."""
        self._metadata["cost"] = cost
        return self

    def with_inputs(self, inputs: dict[str, Any]) -> "StepBuilder":
        """Set step inputs."""
        self._inputs = inputs
        return self

    def with_depends_on(self, dependencies: list[str]) -> "StepBuilder":
        """Set step dependencies."""
        self._depends_on = dependencies
        return self

    def with_max_retries(self, max_retries: int) -> "StepBuilder":
        """Set max retries."""
        self._max_retries = max_retries
        return self

    def with_metadata(self, metadata: dict[str, Any]) -> "StepBuilder":
        """Set step metadata."""
        self._metadata.update(metadata)
        return self

    def build(self) -> Step:
        """Build the Step object."""
        return Step(
            id=self._id,
            action=self._action,
            inputs=self._inputs,
            depends_on=self._depends_on,
            metadata=self._metadata,
            max_retries=self._max_retries,
        )


class PlanBuilder:
    """Fluent builder for creating Plan objects with various dependency patterns."""

    def __init__(self, task_id: str) -> None:
        self._task_id = task_id
        self._plan_id = "plan-default"
        self._steps: list[Step] = []
        self._estimated_cost = 0.0
        self._estimated_time_seconds = 10.0
        self._reasoning = "Generated by test builder"

    def with_id(self, plan_id: str) -> "PlanBuilder":
        """Set plan ID."""
        self._plan_id = plan_id
        return self

    def with_steps(self, steps: list[Step]) -> "PlanBuilder":
        """Set explicit steps."""
        self._steps = steps
        total_cost = sum(s.metadata.get("cost", 1.0) for s in steps)
        self._estimated_cost = total_cost
        return self

    def with_linear_steps(self, count: int, action: str = "default_action") -> "PlanBuilder":
        """Create N linearly dependent steps."""
        self._steps = []
        for i in range(count):
            deps = [f"step-{i-1}"] if i > 0 else []
            step = StepBuilder(f"step-{i}").with_action(action).with_depends_on(deps).build()
            self._steps.append(step)
        self._estimated_cost = float(count)
        return self

    def with_diamond_steps(self, action: str = "default_action") -> "PlanBuilder":
        """Create diamond dependency graph: A -> B, A -> C, B -> D, C -> D."""
        self._steps = [
            StepBuilder("step-A").with_action(action).build(),
            StepBuilder("step-B").with_action(action).with_depends_on(["step-A"]).build(),
            StepBuilder("step-C").with_action(action).with_depends_on(["step-A"]).build(),
            StepBuilder("step-D").with_action(action).with_depends_on(["step-B", "step-C"]).build(),
        ]
        self._estimated_cost = 4.0
        return self

    def with_custom_steps(self, step_configs: list[dict[str, Any]]) -> "PlanBuilder":
        """Create steps from custom configurations."""
        self._steps = []
        for config in step_configs:
            builder = StepBuilder(config["id"]).with_action(config.get("action", "default_action"))
            if "cost" in config:
                builder.with_cost(config["cost"])
            if "depends_on" in config:
                builder.with_depends_on(config["depends_on"])
            if "max_retries" in config:
                builder.with_max_retries(config["max_retries"])
            self._steps.append(builder.build())
        total_cost = sum(s.metadata.get("cost", 1.0) for s in self._steps)
        self._estimated_cost = total_cost
        return self

    def with_estimated_cost(self, cost: float) -> "PlanBuilder":
        """Override estimated cost."""
        self._estimated_cost = cost
        return self

    def with_estimated_time(self, seconds: float) -> "PlanBuilder":
        """Set estimated time."""
        self._estimated_time_seconds = seconds
        return self

    def build(self) -> Plan:
        """Build the Plan object."""
        if not self._steps:
            self.with_linear_steps(1)
        return Plan(
            id=self._plan_id,
            task_id=self._task_id,
            steps=self._steps,
            estimated_cost=self._estimated_cost,
            estimated_time_seconds=self._estimated_time_seconds,
            reasoning=self._reasoning,
        )


class StepHandlerFactory:
    """Factory for creating realistic step handlers."""

    @staticmethod
    def success_handler() -> Callable:
        """Handler that always succeeds."""
        def handler(step: Step) -> StepResult:
            return StepResult(success=True)
        return handler

    @staticmethod
    def failure_handler() -> Callable:
        """Handler that always fails."""
        def handler(step: Step) -> StepResult:
            return StepResult(success=False, error="Intentional failure")
        return handler

    @staticmethod
    def retry_handler(fail_count: int = 1) -> Callable:
        """Handler that fails N times then succeeds."""
        state = {"attempts": 0}

        def handler(step: Step) -> StepResult:
            state["attempts"] += 1
            if state["attempts"] <= fail_count:
                return StepResult(success=False, error=f"Attempt {state['attempts']} failed")
            return StepResult(success=True)

        return handler

    @staticmethod
    def expensive_handler(cost_multiplier: float = 1.0) -> Callable:
        """Handler that succeeds but costs heavily (cost stored in step.metadata)."""
        def handler(step: Step) -> StepResult:
            return StepResult(success=True)
        return handler

    @staticmethod
    def mixed_handler(success_sequence: list[bool]) -> Callable:
        """Handler that follows a predefined success/failure sequence."""
        state = {"index": 0}

        def handler(step: Step) -> StepResult:
            if state["index"] >= len(success_sequence):
                return StepResult(success=True)
            success = success_sequence[state["index"]]
            state["index"] += 1
            if success:
                return StepResult(success=True)
            return StepResult(success=False, error="Step failed")

        return handler


def generate_linear_plan(task_id: str, step_count: int, action: str = "default_action") -> Plan:
    """Generate a linear N-step plan."""
    return PlanBuilder(task_id).with_linear_steps(step_count, action=action).build()


def generate_diamond_plan(task_id: str, action: str = "default_action") -> Plan:
    """Generate a diamond dependency graph plan."""
    return PlanBuilder(task_id).with_diamond_steps(action=action).build()


def generate_expensive_plan(task_id: str, step_count: int, cost_per_step: float) -> Plan:
    """Generate a plan with expensive steps."""
    builder = PlanBuilder(task_id)
    steps = []
    for i in range(step_count):
        deps = [f"step-{i-1}"] if i > 0 else []
        step = StepBuilder(f"step-{i}").with_cost(cost_per_step).with_depends_on(deps).build()
        steps.append(step)
    return builder.with_steps(steps).with_estimated_cost(cost_per_step * step_count).build()
