"""Plan contract: execution plan for tasks."""

from dataclasses import dataclass, field
from enum import Enum


class StepStatus(Enum):
    """Status of a plan step."""

    PENDING = "pending"
    READY = "ready"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class Step:
    """A single step in an execution plan.

    Steps represent atomic units of work that can be executed.
    Each step can depend on other steps completing first.

    Retry semantics:
    - max_retries: maximum number of retry attempts (0 = no retries, 3 = up to 3 retries)
    - retry_count: current number of retry attempts already performed
    - Total attempts possible: 1 (initial) + max_retries (retries)
    """

    id: str
    action: str
    inputs: dict = field(default_factory=dict)
    depends_on: list[str] = field(default_factory=list)
    status: StepStatus = StepStatus.PENDING
    retry_count: int = 0
    max_retries: int = 3
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate step on creation."""
        if not self.id:
            raise ValueError("Step id cannot be empty")
        if not self.action:
            raise ValueError("Step action cannot be empty")
        if self.max_retries < 0:
            raise ValueError("max_retries cannot be negative")

    def can_execute(self) -> bool:
        """Check if this step is ready to execute."""
        return self.status == StepStatus.READY

    def has_failed(self) -> bool:
        """Check if this step has permanently failed (status=FAILED and retries exhausted).

        Returns True only when the step has failed AND there are no more retries available.
        This indicates the step cannot be recovered through retry attempts.
        """
        return self.status == StepStatus.FAILED and self.retry_count >= self.max_retries

    def can_retry(self) -> bool:
        """Check if this step can be retried.

        Returns True if the step failed but still has retry attempts available.
        Once this returns False, the step is permanently failed.
        """
        return self.status == StepStatus.FAILED and self.retry_count < self.max_retries


@dataclass
class Plan:
    """Execution plan for a task.

    A plan is a sequence of steps with dependencies.
    Plans are generated by the planner agent and executed by the runtime.
    """

    id: str
    task_id: str
    steps: list[Step] = field(default_factory=list)
    estimated_cost: float = 0.0
    estimated_time_seconds: float = 0.0
    reasoning: str = ""
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate plan on creation."""
        if not self.id:
            raise ValueError("Plan id cannot be empty")
        if not self.task_id:
            raise ValueError("Plan task_id cannot be empty")
        if self.estimated_cost < 0:
            raise ValueError("estimated_cost cannot be negative")
        if self.estimated_time_seconds < 0:
            raise ValueError("estimated_time_seconds cannot be negative")

        # Validate step dependencies
        step_ids = {step.id for step in self.steps}
        for step in self.steps:
            for dep in step.depends_on:
                if dep not in step_ids:
                    raise ValueError(f"Step {step.id} depends on unknown step {dep}")

        # Detect circular dependencies using DFS
        self._validate_no_circular_dependencies()

    def _validate_no_circular_dependencies(self) -> None:
        """Detect circular dependencies in the step graph using DFS."""
        # Build adjacency list for dependency graph
        graph: dict[str, list[str]] = {step.id: step.depends_on for step in self.steps}

        visited: set[str] = set()
        rec_stack: set[str] = set()

        def has_cycle(node: str) -> bool:
            visited.add(node)
            rec_stack.add(node)

            for neighbor in graph.get(node, []):
                if neighbor not in visited:
                    if has_cycle(neighbor):
                        return True
                elif neighbor in rec_stack:
                    return True

            rec_stack.remove(node)
            return False

        # Check each node for cycles
        for step in self.steps:
            if step.id not in visited:
                if has_cycle(step.id):
                    raise ValueError(f"Circular dependency detected in plan {self.id}")

    def get_steps_by_status(self, status: StepStatus) -> list[Step]:
        """Get all steps with a specific status."""
        return [step for step in self.steps if step.status == status]

    def is_executable(self) -> bool:
        """Check if plan is ready to execute."""
        return len(self.steps) > 0 and all(step.id for step in self.steps)

    def get_ready_steps(self) -> list[Step]:
        """Get all steps that are ready to execute (dependencies met)."""
        return [step for step in self.steps if step.can_execute()]

    def all_steps_completed(self) -> bool:
        """Check if all steps have completed (successfully or not)."""
        if not self.steps:
            return False
        return all(step.status in {StepStatus.COMPLETED, StepStatus.FAILED, StepStatus.SKIPPED}
                  for step in self.steps)
